spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/webflux-test
    username: root
    password: 12345
  sql:
    init:
      mode: always
logging:
  level:
    org.springframework.r2dbc.core: debug
